# docker-compose.yml
services:
  web:
    build: .
    command: python /build/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/build
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data: