# Generated by Django 5.0.2 on 2024-03-08 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('isbulk', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('accessLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('date_inservice', models.DateField(blank=True, null=True)),
                ('date_outservice', models.DateField(blank=True, null=True)),
                ('date_scanned', models.DateField(blank=True, null=True)),
                ('ItemBestelling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.bestelling')),
                ('ItemTypes', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.itemtypes')),
                ('ItemLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location')),
                ('ipAdress', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('DienstLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location')),
            ],
        ),
        migrations.AddField(
            model_name='bestelling',
            name='BestellingLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('UserRole', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.role')),
                ('userDienst', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='userDienst', to='inventoryAPP.dienst')),
            ],
        ),
        migrations.CreateModel(
            name='userItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.user')),
            ],
        ),
    ]
