# Generated by Django 5.0.2 on 2024-02-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=100)),
                ('date_inservice', models.DateField()),
                ('date_outservice', models.DateField()),
                ('date_scanned', models.DateField()),
            ],
        ),
    ]
