# Generated by Django 5.0.2 on 2024-02-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_inservice',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_outservice',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_scanned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
