# Generated by Django 5.0.2 on 2024-03-08 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0002_auto_20240308_2356'),
    ]

    operations = [
        
    ]
