# Generated by Django 5.0.2 on 2024-03-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0002_auto_20240308_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestelling',
            name='BestellingLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryAPP.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_inservice',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_outservice',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_scanned',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
