# Generated by Django 5.0.2 on 2024-02-25 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0002_alter_item_date_inservice_alter_item_date_outservice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestelling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(max_length=100)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('isbulk', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('shortname', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('accessLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='ItemBestelling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.bestelling'),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemTypes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryAPP.itemtypes'),
        ),
        migrations.CreateModel(
            name='Dienst',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('DienstLocation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location')),
            ],
        ),
        migrations.AddField(
            model_name='bestelling',
            name='BestellingLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='ItemLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('UserRole', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.role')),
            ],
        ),
    ]
