# Generated by Django 5.0.2 on 2024-02-25 01:21

from django.db import migrations


# Generated by Django 5.0.2 on 2024-02-25 01:21

# Generated by Django 5.0.2 on 2024-02-25 01:21

from django.db import migrations


from django.db import migrations
from inventoryAPP.models import Role, Location, Bestelling, ItemTypes, Dienst, User, Item

def create_default_roles(apps, schema_editor):
    Role.objects.bulk_create([
        Role(name='User', accessLevel=0),
        Role(name='Scanner', accessLevel=1),
        Role(name='Admin', accessLevel=2),
        Role(name='SuperAdmin', accessLevel=3),
    ])

def create_default_locations(apps, schema_editor):
    Location.objects.bulk_create([
        Location(name='Location1', address='Address1', city='City1', state='State1', zip='Zip1', country='Country1'),
        Location(name='Location2', address='Address2', city='City2', state='State2', zip='Zip2', country='Country2'),
        # Add more locations as needed
    ])

def create_default_bestellings(apps, schema_editor):
    Bestelling.objects.bulk_create([
        Bestelling(unitPrice=10.0, quantity=5, date='2024-02-25', BestellingLocation_id=1),
        Bestelling(unitPrice=15.0, quantity=3, date='2024-02-26', BestellingLocation_id=2),
        # Add more bestellings as needed
    ])

def create_default_item_types(apps, schema_editor):
    ItemTypes.objects.bulk_create([
        ItemTypes(name='Type1', code='Code1', quantity=10, isbulk=True),
        ItemTypes(name='Type2', code='Code2', quantity=5, isbulk=False),
        # Add more item types as needed
    ])

def create_default_diensts(apps, schema_editor):
    Dienst.objects.bulk_create([
        Dienst(name='Dienst1'),
        Dienst(name='Dienst2'),
        # Add more diensts as needed
    ])

def create_default_users(apps, schema_editor):
    User.objects.bulk_create([
        User(name='User1', password='password1', UserRole_id=1),  # Assuming the role with ID 1 is 'User'
        User(name='Scanner1', password='password2', UserRole_id=2),  # Assuming the role with ID 2 is 'Scanner'
        User(name='Admin1', password='password3', UserRole_id=3),  # Assuming the role with ID 3 is 'Admin'
        User(name='SuperAdmin1', password='password4', UserRole_id=4),  # Assuming the role with ID 4 is 'SuperAdmin'
        # Add more users as needed
    ])

def create_default_items(apps, schema_editor):
    Item.objects.bulk_create([
        Item(name='Item1', code='Code1', ItemTypes_id=1, ItemLocation_id=1, ItemBestelling_id=1),
        Item(name='Item2', code='Code2', ItemTypes_id=2, ItemLocation_id=2, ItemBestelling_id=2),
        # Add more items as needed
    ])

class Migration(migrations.Migration):

    dependencies = [
        # your dependencies
        ('inventoryAPP', '0003_bestelling_itemtypes_location_role_and_more'),
        ]

    operations = [
        # other operations...
        migrations.RunPython(create_default_roles),
        migrations.RunPython(create_default_locations),
        migrations.RunPython(create_default_bestellings),
        migrations.RunPython(create_default_item_types),
        migrations.RunPython(create_default_diensts),
        migrations.RunPython(create_default_users),
        migrations.RunPython(create_default_items),
    ]