# Generated by Django 5.0.2 on 2024-03-27 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0003_alter_bestelling_bestellinglocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemLocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='ItemTypes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.itemtypes'),
        ),
    ]
