# Generated by Django 5.0.2 on 2024-02-25 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0004_auto_20240225_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserRole',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.role'),
        ),
    ]
