# Generated by Django 5.0.2 on 2024-02-26 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0005_alter_user_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='ItemTypes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.itemtypes'),
        ),
    ]
