# Generated by Django 5.0.2 on 2024-03-07 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryAPP', '0006_alter_item_itemtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestelling',
            name='date',
        ),
        migrations.AddField(
            model_name='bestelling',
            name='supplier',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userDienst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.dienst'),
        ),
        migrations.CreateModel(
            name='userItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventoryAPP.user')),
            ],
        ),
    ]
